# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20170314_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name': 'Body', 'verbose_name_plural': 'Bodies'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Mark', 'verbose_name_plural': 'Marks'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AddField(
            model_name='model',
            name='kind',
            field=models.CharField(default='A', max_length=1, verbose_name='kind'),
            preserve_default=False,
        ),
    ]
