# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20170317_2301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Body',
            new_name='Evo',
        ),
        migrations.AlterModelOptions(
            name='evo',
            options={'verbose_name': 'Evolution', 'verbose_name_plural': 'Evolutions'},
        ),
    ]
