# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20170318_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evo',
            name='name',
            field=models.CharField(max_length=12, verbose_name='evo'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='country',
            field=models.CharField(max_length=12, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=12, unique=True, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=12, verbose_name='model'),
        ),
    ]
